//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarajaApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mpesa_setupEntities : DbContext
    {
        public mpesa_setupEntities()
            : base("name=mpesa_setupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DarajaApiCredential> DarajaApiCredentials { get; set; }
        public virtual DbSet<MpesaExpressSetup> MpesaExpressSetups { get; set; }
        public virtual DbSet<MpesaCallBackData> MpesaCallBackDatas { get; set; }
    }
}
