//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarajaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpesaExpressSetup
    {
        public int ExpressID { get; set; }
        public Nullable<decimal> ShortCode { get; set; }
        public string PassKey { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> CustomerPhoneNo { get; set; }
        public string Callbackurl { get; set; }
        public string AccountReference { get; set; }
        public string TransactionDescription { get; set; }
        public string TransactionType { get; set; }
    }
}
