//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarajaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpesaCallBackData
    {
        public int ID { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
